
let serviceLabels = new Map([
                  ["http://remix.numbersintonotes.net/vocab#lengthCompatibility", "Matching Length"],
                  ["http://remix.numbersintonotes.net/vocab#instrumentCompatibility", "Compatible Instrument"],
                  ["http://remix.numbersintonotes.net/vocab#keyCompatibility", "Key Compatibility"] ])

let instrumentLabels = new Map([
     [ 'http://fast-project.annalist.net/annalist/c/FAST_musical_instruments_catalogue/d/Instrument/violoncello/entity_data.ttl', 'Cello' ],
     [ 'http://fast-project.annalist.net/annalist/c/FAST_musical_instruments_catalogue/d/Instrument/clarinet/entity_data.ttl', 'Clarinet' ],
     [ 'http://fast-project.annalist.net/annalist/c/FAST_musical_instruments_catalogue/d/Instrument/violin/entity_data.ttl', 'Violin' ],
     [ 'http://fast-project.annalist.net/annalist/c/FAST_musical_instruments_catalogue/d/Instrument/viola/entity_data.ttl', 'Viola' ],
     [ 'http://fast-project.annalist.net/annalist/c/FAST_musical_instruments_catalogue/d/Instrument/banjo/entity_data.ttl', 'Banjo' ],
     [ 'http://fast-project.annalist.net/annalist/c/FAST_musical_instruments_catalogue/d/Instrument/tuba/entity_data.ttl', 'Tuba' ],
     [ 'http://fast-project.annalist.net/annalist/c/FAST_musical_instruments_catalogue/d/Instrument/piano/entity_data.ttl', 'Piano' ]
    ])

let instrumentDetails = new Map([
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_cornett', {label: 'Tenor Cornett', minmidi: 48, maxmidi: 71 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_mandola', {label: 'Alto Mandola', minmidi: 48, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/dulcimer', {label: 'Dulcimer', minmidi: 48, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/orff_soprano_metallophone', {label: 'Orff Soprano Metallophone', minmidi: 72, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_clarinet', {label: 'Soprano Clarinet', minmidi: 59, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/cornettino', {label: 'Cornettino', minmidi: 72, maxmidi: 95 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/double_contrabass_flute', {label: 'Double Contrabass Flute', minmidi: 24, maxmidi: 53 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/electric_guitar_treble_clef', {label: 'Electric Guitar', minmidi: 40, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_viol', {label: 'Alto Viol', minmidi: 45, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabasses', {label: 'Contrabasses', minmidi: 28, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/a_trumpet', {label: 'A Trumpet', minmidi: 51, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/treble_flute', {label: 'Treble Flute', minmidi: 67, maxmidi: 100 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sine_synth', {label: 'Sine Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/strings', {label: 'Strings', minmidi: 24, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto', {label: 'Alto', minmidi: 55, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_c12g', {label: '12 Hole G Chromatic Harmonica', minmidi: 55, maxmidi: 91 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_cornamuse', {label: 'Tenor Cornamuse', minmidi: 48, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/flute', {label: 'Flute', minmidi: 60, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/pocket_trumpet', {label: 'Pocket Trumpet', minmidi: 52, maxmidi: 80 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alphorn', {label: 'Alphorn', minmidi: 34, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_crumhorn', {label: 'Bass Crumhorn', minmidi: 41, maxmidi: 55 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_banjo', {label: 'Tenor Banjo', minmidi: 48, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_wagner_tuba', {label: 'F Wagner Tuba', minmidi: 35, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/accordion', {label: 'Accordion', minmidi: 36, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/pardessus_de_viole', {label: 'Pardessus de viole', minmidi: 55, maxmidi: 91 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/db_piccolo', {label: 'D♭ Piccolo', minmidi: 75, maxmidi: 106 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_alto_ophicleide', {label: 'F Alto Ophicleide', minmidi: 52, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/orff_alto_xylophone', {label: 'Orff Alto Xylophone', minmidi: 60, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/fretless_electric_bass', {label: 'Fretless Electric Bass', minmidi: 28, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soundtrack_synth', {label: 'Soundtrack Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/marimba', {label: 'Marimba', minmidi: 45, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_trumpet', {label: 'E♭ Trumpet', minmidi: 57, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/viola_da_gamba', {label: 'Viola da gamba', minmidi: 33, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/kuhlohorn', {label: 'Kuhlohorn', minmidi: 52, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_saxophone', {label: 'Soprano Saxophone', minmidi: 56, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/xylophone', {label: 'Xylophone', minmidi: 65, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/quena', {label: 'Quena', minmidi: 72, maxmidi: 92 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/aulochrome', {label: 'Aulochrome', minmidi: 56, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/cromorne', {label: 'Cromorne', minmidi: 60, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/e_dizi', {label: 'E Dizi', minmidi: 71, maxmidi: 97 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/d_duduk', {label: 'Duduk', minmidi: 71, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/serpent', {label: 'Serpent', minmidi: 36, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/g_duduk', {label: 'G Duduk', minmidi: 64, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/cornett', {label: 'Cornett', minmidi: 60, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/cello_steel_drums', {label: 'Cello Steel Drums', minmidi: 47, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_clarinet', {label: 'C Clarinet', minmidi: 52, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_gemshorn', {label: 'Bass Gemshorn', minmidi: 53, maxmidi: 68 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_gemshorn', {label: 'Tenor Gemshorn', minmidi: 60, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sitar', {label: 'Sitar', minmidi: 36, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_sackbut', {label: 'Alto Sackbut', minmidi: 45, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_saxophone', {label: 'Alto Saxophone', minmidi: 49, maxmidi: 82 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_steel_drums', {label: 'Tenor Steel Drums', minmidi: 52, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sopranino_shawm', {label: 'Sopranino Shawm', minmidi: 65, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/d_trumpet', {label: 'D Trumpet', minmidi: 56, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_flute', {label: 'Soprano Flute', minmidi: 63, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/balalaika', {label: 'Balalaika', minmidi: 64, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/violone', {label: 'Violone', minmidi: 31, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_bass_ocarina', {label: 'C Bass Ocarina', minmidi: 48, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_sheng', {label: 'Alto Sheng', minmidi: 48, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/d_tin_whistle', {label: 'D Tin Whistle', minmidi: 74, maxmidi: 98 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/gemshorn', {label: 'Gemshorn', minmidi: 72, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_tuba', {label: 'F Tuba', minmidi: 26, maxmidi: 64 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sci_fi_synth', {label: 'Sci-fi Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_steel_drums', {label: 'Soprano Steel Drums', minmidi: 60, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/low_c_horn', {label: 'Horn in C', minmidi: 34, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/choir_synth', {label: 'Choir Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/trumpet', {label: 'Trumpet', minmidi: 52, maxmidi: 80 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/honky_tonk_piano', {label: 'Honky Tonk Piano', minmidi: 21, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/ab_horn', {label: 'Horn in A♭', minmidi: 42, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/upright_piano', {label: 'Upright Piano', minmidi: 21, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bassoon', {label: 'Bassoon', minmidi: 34, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/subcontra_alto_flute', {label: 'Sub Contra-alto Flute', minmidi: 31, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_sarrusophone', {label: 'Soprano Sarrusophone', minmidi: 56, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/echoes_synth', {label: 'Echoes Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/men', {label: 'Men', minmidi: 41, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_sheng', {label: 'Bass Sheng', minmidi: 36, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_c16c', {label: '16 Hole C Chromatic Harmonica', minmidi: 48, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_kelhorn', {label: 'Alto Kelhorn', minmidi: 53, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/duduk', {label: 'Duduk', minmidi: 66, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/women', {label: 'Women', minmidi: 55, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/heckelphone_clarinet', {label: 'Heckelphone-clarinet', minmidi: 50, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_alto_ocarina', {label: 'C Alto Ocarina', minmidi: 60, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/brass_synthesizer', {label: 'Brass Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/balalaika_bass', {label: 'Bass Balalaika', minmidi: 40, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_tuba', {label: 'B♭ Tuba', minmidi: 28, maxmidi: 58 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/treble_viol', {label: 'Treble Viol', minmidi: 50, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/poly_synth', {label: 'Poly Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/6_string_electric_bass', {label: '6-str. Electric Bass', minmidi: 23, maxmidi: 70 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/melody_saxophone', {label: 'Melody Saxophone', minmidi: 46, maxmidi: 77 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/guitar_steel_drums', {label: 'Guitar Steel Drums', minmidi: 54, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/guitar_nylon_treble_clef', {label: 'Guitar', minmidi: 40, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_synthesizer', {label: 'Bass Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/e_horn', {label: 'E Horn', minmidi: 38, maxmidi: 71 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_trumpet', {label: 'Bass Trumpet', minmidi: 39, maxmidi: 66 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/steel_drums', {label: 'Steel Drums', minmidi: 36, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_trombone', {label: 'Bass Trombone', minmidi: 32, maxmidi: 68 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/ukulele', {label: 'Ukulele', minmidi: 60, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/slide_trumpet', {label: 'Slide Trumpet', minmidi: 52, maxmidi: 80 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/orff_alto_metallophone', {label: 'Orff Alto Metallophone', minmidi: 60, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/garklein_recorder', {label: 'Garklein Recorder', minmidi: 84, maxmidi: 105 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/chalumeau', {label: 'Chalumeau', minmidi: 48, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonium', {label: 'Harmonium', minmidi: 29, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_flute', {label: 'Bass Flute', minmidi: 48, maxmidi: 77 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contra_alto_clarinet', {label: 'Contra-alto Clarinet', minmidi: 30, maxmidi: 70 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/saxhorn', {label: 'Saxhorn', minmidi: 45, maxmidi: 72 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/danso', {label: 'Danso', minmidi: 67, maxmidi: 91 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/a_horn', {label: 'Horn in A', minmidi: 43, maxmidi: 76 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sopranissimo_saxophone', {label: 'Sopranissimo Saxophone', minmidi: 68, maxmidi: 92 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sopranino_recorder', {label: 'Sopranino Recorder', minmidi: 77, maxmidi: 100 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/rauschpfeife', {label: 'Rauschpfeife', minmidi: 60, maxmidi: 76 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/orff_soprano_xylophone', {label: 'Orff Soprano Xylophone', minmidi: 72, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_duduk', {label: 'C Duduk', minmidi: 69, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_harmonica_hohner', {label: 'Bass Hohner Harmonica', minmidi: 28, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/glockenspiel', {label: 'Glockenspiel', minmidi: 79, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_trombone', {label: 'Tenor Trombone', minmidi: 40, maxmidi: 70 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/oud', {label: 'Oud', minmidi: 36, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_d12high_g', {label: '10 Hole High G Diatonic Harmonica', minmidi: 67, maxmidi: 103 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/electric_guitar', {label: 'Electric Guitar', minmidi: 40, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/oboe', {label: 'Oboe', minmidi: 58, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_bass_ophicleide', {label: 'B♭ Bass Ophicleide', minmidi: 33, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/violas', {label: 'Violas', minmidi: 48, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/5_string_electric_bass_high_c', {label: '5-str. Electric Bass', minmidi: 23, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/d_clarinet', {label: 'D Clarinet', minmidi: 54, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/g_dizi', {label: 'G Dizi', minmidi: 74, maxmidi: 100 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/trombone', {label: 'Trombone', minmidi: 40, maxmidi: 71 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_bugle', {label: 'Alto Bugle', minmidi: 62, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/melodica', {label: 'Melodica', minmidi: 53, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass', {label: 'Bass', minmidi: 41, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabass_sarrusophone', {label: 'Contrabass Sarrusophone', minmidi: 25, maxmidi: 53 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_bugle', {label: 'Soprano Bugle', minmidi: 67, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/goblins_synth', {label: 'Goblins Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baroque_oboe', {label: 'Baroque Oboe', minmidi: 60, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/recorder', {label: 'Recorder', minmidi: 72, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_sheng', {label: 'Soprano Sheng', minmidi: 55, maxmidi: 90 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_sackbut', {label: 'Bass Sackbut', minmidi: 36, maxmidi: 70 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_tuba', {label: 'C Tuba', minmidi: 26, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_c12tenor_c', {label: '12 Hole Tenor C Chromatic Harmonica', minmidi: 48, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_c14c', {label: '14 Hole C Chromatic Harmonica', minmidi: 55, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/clarinet', {label: 'Clarinet', minmidi: 50, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/b_duduk', {label: 'B Duduk', minmidi: 68, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/a_dizi', {label: 'A Dizi', minmidi: 76, maxmidi: 102 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/lute', {label: 'Lute', minmidi: 33, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_sheng', {label: 'Tenor Sheng', minmidi: 44, maxmidi: 78 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/metallophone', {label: 'Metallophone', minmidi: 60, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_tuba_treble', {label: 'B♭ Tuba', minmidi: 28, maxmidi: 58 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabass_flute', {label: 'Contrabass Flute', minmidi: 36, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baritone_saxophone', {label: 'Baritone Saxophone', minmidi: 37, maxmidi: 70 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/greatbass_kelhorn', {label: 'Greatbass Kelhorn', minmidi: 36, maxmidi: 50 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contralto', {label: 'Contralto', minmidi: 55, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bouzouki_3_course', {label: 'Bouzouki', minmidi: 50, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contra_alto_flute', {label: 'Contra-alto Flute', minmidi: 43, maxmidi: 76 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/celo', {label: 'Čelo', minmidi: 3, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tuned_gongs', {label: 'Tuned Gongs', minmidi: 45, maxmidi: 57 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/brass', {label: 'Brass', minmidi: 24, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tuba', {label: 'Tuba', minmidi: 28, maxmidi: 58 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/ukulele_low_g', {label: 'Ukulele (Low G)', minmidi: 55, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/a_cornet', {label: 'A Cornet', minmidi: 51, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/mezzo_soprano', {label: 'Mezzo-soprano', minmidi: 57, maxmidi: 77 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_trumpet', {label: 'F Trumpet', minmidi: 65, maxmidi: 82 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bflat_tin_whistle', {label: 'B♭ Tin Whistle', minmidi: 70, maxmidi: 94 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/helicon', {label: 'Helicon', minmidi: 28, maxmidi: 58 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/metallic_synth', {label: 'Metallic Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/didgeridoo', {label: 'Didgeridoo', minmidi: 24, maxmidi: 36 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_saxophone', {label: 'Tenor Saxophone', minmidi: 44, maxmidi: 77 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/greatbass_recorder', {label: 'Greatbass Recorder', minmidi: 48, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_quena', {label: 'F Quena', minmidi: 65, maxmidi: 85 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/reed_organ', {label: 'Reed Organ', minmidi: 29, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/cornamuse', {label: 'Cornamuse', minmidi: 60, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/english_flageolet', {label: 'English Flageolet', minmidi: 74, maxmidi: 98 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_tuba_treble', {label: 'E♭ Tuba', minmidi: 26, maxmidi: 64 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_baroque_trumpet', {label: 'Baroque Trumpet in E♭', minmidi: 63, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/atmosphere_synth', {label: 'Atmosphere Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/euphonium', {label: 'Euphonium', minmidi: 40, maxmidi: 70 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/irish_flute', {label: 'Irish Flute', minmidi: 62, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_duduk', {label: 'B♭ Duduk', minmidi: 67, maxmidi: 82 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/a_clarinet', {label: 'A Clarinet', minmidi: 49, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/saw_synth', {label: 'Saw Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/12_string_guitar', {label: '12-string Guitar', minmidi: 40, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_sarrusophone', {label: 'Alto Sarrusophone', minmidi: 49, maxmidi: 80 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_bass_trumpet', {label: 'Bass Trumpet in C', minmidi: 39, maxmidi: 66 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/lupophone', {label: 'Lupophone', minmidi: 45, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/a_bass_duduk', {label: 'A Bass Duduk', minmidi: 54, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/basset_horn', {label: 'Basset Horn', minmidi: 41, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/berda', {label: 'Berda', minmidi: 28, maxmidi: 66 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_crumhorn', {label: 'Tenor Crumhorn', minmidi: 48, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bagpipe', {label: 'Bagpipe', minmidi: 65, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baroque_trumpet', {label: 'Baroque Trumpet', minmidi: 58, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/flexatone', {label: 'Flexatone', minmidi: 76, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sarrusophone', {label: 'Sarrusophone', minmidi: 56, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/octavin', {label: 'Octavin', minmidi: 56, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/horagai', {label: 'Horagai', minmidi: 24, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabass_saxophone', {label: 'Contrabass Saxophone', minmidi: 25, maxmidi: 53 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_gemshorn', {label: 'Soprano Gemshorn', minmidi: 72, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_sarrusophone', {label: 'Bass Sarrusophone', minmidi: 32, maxmidi: 63 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contra_guitar', {label: 'Contra Guitar', minmidi: 31, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_baroque_trumpet', {label: 'Baroque Trumpet in C', minmidi: 60, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sopranino_sarrusophone', {label: 'Sopranino Sarrusophone', minmidi: 61, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabass_bugle', {label: 'Contrabass Bugle', minmidi: 43, maxmidi: 55 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/rag_dung', {label: 'Rag Dung', minmidi: 34, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/trombone_treble', {label: 'Trombone', minmidi: 40, maxmidi: 71 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/vuvuzela', {label: 'Vuvuzela', minmidi: 35, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_d12c', {label: '10 Hole C Diatonic Harmonica', minmidi: 60, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_cornet', {label: 'E♭ Cornet', minmidi: 57, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_soprano_ocarina', {label: 'C Soprano Ocarina', minmidi: 72, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_duduk', {label: 'F Duduk', minmidi: 74, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/nyckelharpa', {label: 'Nyckelharpa', minmidi: 48, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_clarinet', {label: 'Bass Clarinet', minmidi: 37, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baritone_sarrusophone', {label: 'Baritone Sarrusophone', minmidi: 37, maxmidi: 68 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_clarinet', {label: 'B♭ Clarinet', minmidi: 50, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baritone_oboe', {label: 'Baritone Oboe', minmidi: 47, maxmidi: 76 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/hyperbass_flute', {label: 'Hyperbass Flute', minmidi: 12, maxmidi: 42 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/a_bass_clarinet_bass_clef', {label: 'A Bass Clarinet (Bass Clef)', minmidi: 36, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/mandola', {label: 'Mandola', minmidi: 48, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_piccolo_trumpet', {label: 'Piccolo Trumpet in B♭', minmidi: 59, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/musical_saw', {label: 'Musical Saw', minmidi: 64, maxmidi: 100 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/piccolo', {label: 'Piccolo', minmidi: 74, maxmidi: 105 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_chordet', {label: '20 Hole Chordet Harmonica', minmidi: 58, maxmidi: 66 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/guitar_steel_treble_clef', {label: 'Guitar', minmidi: 40, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/basset_clarinet', {label: 'Basset Clarinet', minmidi: 45, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/Winds', {label: 'Winds', minmidi: 24, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_cornamuse', {label: 'Bass Cornamuse', minmidi: 41, maxmidi: 55 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/heckelphone', {label: 'Heckelphone', minmidi: 45, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/a_bass_clarinet', {label: 'A Bass Clarinet', minmidi: 36, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_eb_tuba', {label: 'Bass Tuba in E♭', minmidi: 26, maxmidi: 64 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/violoncello', {label: 'Violoncello', minmidi: 36, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tin_whistle', {label: 'Tin Whistle', minmidi: 72, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/halo_synth', {label: 'Halo Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/e_duduk', {label: 'E Duduk', minmidi: 73, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_crumhorn', {label: 'Soprano Crumhorn', minmidi: 60, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/glass_harmonica', {label: 'Glass Harmonica', minmidi: 53, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baritone_guitar', {label: 'Baritone Guitar', minmidi: 35, maxmidi: 78 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabass_marimba', {label: 'Contrabass Marimba', minmidi: 21, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_harmonica_huang', {label: 'Bass Huang Harmonica', minmidi: 28, maxmidi: 40 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_alto_ophicleide', {label: 'E♭ Alto Ophicleide', minmidi: 51, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/clavinet', {label: 'Clavinet', minmidi: 29, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/viola', {label: 'Viola', minmidi: 48, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_cornett', {label: 'Soprano Cornett', minmidi: 60, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/hand_bells', {label: 'Hand Bells', minmidi: 36, maxmidi: 97 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabassoon', {label: 'Contrabassoon', minmidi: 22, maxmidi: 57 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/octave_mandolin', {label: 'Octave Mandolin', minmidi: 43, maxmidi: 73 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/violin', {label: 'Violin', minmidi: 55, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_alto_horn', {label: 'F Alto Horn', minmidi: 47, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_guitar', {label: 'Soprano Guitar', minmidi: 52, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/piccolo_clarinet', {label: 'Piccolo Clarinet', minmidi: 60, maxmidi: 99 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/piccolo_trumpet', {label: 'Piccolo Trumpet', minmidi: 59, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/balalaika_contrabass', {label: 'Contrabass Balalaika', minmidi: 28, maxmidi: 55 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/voice', {label: 'Voice', minmidi: 40, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/clavichord', {label: 'Clavichord', minmidi: 29, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_tuba', {label: 'E♭ Tuba', minmidi: 26, maxmidi: 64 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/irish_tenor_banjo', {label: 'Irish Tenor Banjo', minmidi: 43, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_ukulele', {label: 'Tenor Ukulele', minmidi: 60, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_cornamuse', {label: 'Alto Cornamuse', minmidi: 55, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/brightness_synth', {label: 'Brightness Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_bass_trumpet', {label: 'E♭ Bass Trumpet', minmidi: 46, maxmidi: 73 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baritone_ukulele', {label: 'Baritone Ukulele', minmidi: 50, maxmidi: 76 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/koto', {label: 'Koto', minmidi: 43, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/mezzo_soprano_saxophone', {label: 'Mezzo-Soprano Saxophone', minmidi: 51, maxmidi: 82 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/electric_bass', {label: 'Electric Bass', minmidi: 28, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_kelhorn', {label: 'Bass Kelhorn', minmidi: 41, maxmidi: 55 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/timpani', {label: 'Timpani', minmidi: 38, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/g_soprano_ocarina', {label: 'G Soprano Ocarina', minmidi: 79, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baritone_horn', {label: 'Baritone Horn', minmidi: 40, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/orff_bass_xylophone', {label: 'Orff Bass Xylophone', minmidi: 48, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bouzouki_4_course', {label: 'Bouzouki', minmidi: 48, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baritone_bugle', {label: 'Baritone Bugle', minmidi: 50, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_cornet', {label: 'B♭ Cornet', minmidi: 52, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/orff_soprano_glockenspiel', {label: 'Orff Soprano Glockenspiel', minmidi: 84, maxmidi: 105 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/countertenor', {label: 'Countertenor', minmidi: 55, maxmidi: 76 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/a_piccolo_trumpet', {label: 'Piccolo Trumpet in A', minmidi: 58, maxmidi: 85 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/musical_glasses', {label: 'Musical Glasses', minmidi: 72, maxmidi: 91 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_flute', {label: 'Alto Flute', minmidi: 55, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_chalumeau', {label: 'Soprano Chalumeau', minmidi: 60, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/oboe_da_caccia', {label: 'Oboe da caccia', minmidi: 53, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/g_alto_ocarina', {label: 'G Alto Ocarina', minmidi: 67, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/ocarina', {label: 'Ocarina', minmidi: 72, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/horn', {label: 'Horn in F', minmidi: 41, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/string_synthesizer', {label: 'String Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_f_tuba', {label: 'Bass Tuba in F', minmidi: 26, maxmidi: 64 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/d_baroque_trumpet', {label: 'Baroque Trumpet in D', minmidi: 62, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_crumhorn', {label: 'Alto Crumhorn', minmidi: 53, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/kazoo', {label: 'Kazoo', minmidi: 41, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/g_horn', {label: 'Horn in G', minmidi: 41, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_chalumeau', {label: 'Alto Chalumeau', minmidi: 53, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sopranino_rauschpfeife', {label: 'Sopranino Rauschpfeife', minmidi: 65, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor', {label: 'Tenor', minmidi: 48, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_alto_ocarina', {label: 'F Alto Ocarina', minmidi: 65, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_guitar', {label: 'Bass Guitar', minmidi: 28, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_c12c', {label: '12 Hole C Chromatic Harmonica', minmidi: 60, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/almglocken', {label: 'Almglocken', minmidi: 60, maxmidi: 105 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_alto_horn', {label: 'E♭ Alto Horn', minmidi: 45, maxmidi: 72 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/crystal_synth', {label: 'Crystal Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/balalaika_alto', {label: 'Alto Balalaika', minmidi: 52, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tuned_klaxon_horns', {label: 'Tuned Klaxon Horns', minmidi: 48, maxmidi: 72 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/5_string_electric_bass', {label: '5-str. Electric Bass', minmidi: 23, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_cornet', {label: 'C Cornet', minmidi: 54, maxmidi: 82 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/balalaika_secunda', {label: 'Secunda Balalaika', minmidi: 57, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/fiscorn', {label: 'Fiscorn', minmidi: 52, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/piccolo_heckelphone', {label: 'Piccolo Heckelphone', minmidi: 63, maxmidi: 92 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_trumpet', {label: 'C Trumpet', minmidi: 54, maxmidi: 82 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/cimbasso', {label: 'Cimbasso', minmidi: 26, maxmidi: 64 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_guitar', {label: 'Alto Guitar', minmidi: 47, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_rauschpfeife', {label: 'Soprano Rauschpfeife', minmidi: 60, maxmidi: 76 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_trombone', {label: 'Soprano Trombone', minmidi: 52, maxmidi: 77 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/e_trumpet', {label: 'E Trumpet', minmidi: 58, maxmidi: 85 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baroque_lute_13_course', {label: 'Lute', minmidi: 33, maxmidi: 77 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_recorder', {label: 'Tenor Recorder', minmidi: 60, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_harmonica', {label: 'Bass Harmonica', minmidi: 28, maxmidi: 40 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/shenai', {label: 'Shenai', minmidi: 62, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/orff_alto_glockenspiel', {label: 'Orff Alto Glockenspiel', minmidi: 72, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/virginal', {label: 'Virginal', minmidi: 29, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_cornamuse', {label: 'Soprano Cornamuse', minmidi: 60, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bowed_synth', {label: 'Bowed Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_trumpet', {label: 'Tenor Trumpet', minmidi: 52, maxmidi: 80 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/11_string_alto_guitar', {label: '11-string Alto Guitar', minmidi: 34, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/pedal_steel_guitar', {label: 'Pedal Steel Guitar', minmidi: 35, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/wagner_tuba', {label: 'Wagner Tuba', minmidi: 35, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/pan_flute', {label: 'Pan Flute', minmidi: 60, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/electric_piano', {label: 'Electric Piano', minmidi: 21, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sopranino_saxophone', {label: 'Sopranino Saxophone', minmidi: 61, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/traverso', {label: 'Traverso', minmidi: 62, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/g_clarinet', {label: 'G Clarinet', minmidi: 47, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/flageolet', {label: 'Flageolet', minmidi: 74, maxmidi: 98 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/d_violone', {label: 'D Violone', minmidi: 26, maxmidi: 55 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/mandolin', {label: 'Mandolin', minmidi: 55, maxmidi: 85 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/d_horn', {label: 'Horn in D', minmidi: 36, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/piano', {label: 'Piano', minmidi: 21, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tubular_bells', {label: 'Chimes', minmidi: 60, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bugarija', {label: 'Bugarija', minmidi: 43, maxmidi: 66 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/violoncellos', {label: 'Violoncellos', minmidi: 36, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sweep_synth', {label: 'Sweep Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_d12d', {label: '10 Hole D Diatonic Harmonica', minmidi: 62, maxmidi: 98 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/celesta', {label: 'Celesta', minmidi: 48, maxmidi: 113 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baryton', {label: 'Baryton', minmidi: 33, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_chalumeau', {label: 'Bass Chalumeau', minmidi: 41, maxmidi: 55 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_horn', {label: 'Horn in E♭', minmidi: 37, maxmidi: 70 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harpsichord', {label: 'Harpsichord', minmidi: 29, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_alto_ocarina', {label: 'B♭­ Alto Ocarina', minmidi: 58, maxmidi: 72 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/d_quena', {label: 'Quena', minmidi: 62, maxmidi: 82 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/shofar', {label: 'Shofar', minmidi: 48, maxmidi: 72 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/erhu', {label: 'Erhu', minmidi: 62, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_shawm', {label: 'Bass Shawm', minmidi: 41, maxmidi: 57 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/marimba_single', {label: 'Marimba', minmidi: 45, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/archlute_14_course', {label: 'Archlute', minmidi: 29, maxmidi: 77 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/xylomarimba', {label: 'Xylomarimba', minmidi: 48, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_cornett', {label: 'Alto Cornett', minmidi: 57, maxmidi: 80 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/balalaika_piccolo', {label: 'Piccolo Balalaika', minmidi: 71, maxmidi: 98 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/euphonium_bugle', {label: 'Euphonium Bugle', minmidi: 50, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_sarrusophone', {label: 'Tenor Sarrusophone', minmidi: 44, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_recorder', {label: 'Alto Recorder', minmidi: 65, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/concertina', {label: 'Concertina', minmidi: 36, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_baroque_trumpet', {label: 'Baroque Trumpet in B♭', minmidi: 58, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/effect_synth', {label: 'Effect Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sopranino_chalumeau', {label: 'Sopranino Chalumeau', minmidi: 65, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/great_bass_shawm', {label: 'Great Bass Shawm', minmidi: 36, maxmidi: 52 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_clarinet', {label: 'E♭ Clarinet', minmidi: 55, maxmidi: 94 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baritone', {label: 'Baritone', minmidi: 43, maxmidi: 64 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/low_bb_horn', {label: 'Horn in B♭ basso', minmidi: 32, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/acoustic_bass', {label: 'Acoustic Bass', minmidi: 28, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/subcontrabass_tuba', {label: 'Sub-Contrabass Tuba', minmidi: 16, maxmidi: 46 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_clarinet', {label: 'Alto Clarinet', minmidi: 43, maxmidi: 80 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/crumhorn', {label: 'Crumhorn', minmidi: 60, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/brac', {label: 'Brač', minmidi: 52, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_bass_ophicleide', {label: 'C Bass Ophicleide', minmidi: 35, maxmidi: 63 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/slide_whistle', {label: 'Slide Whistle', minmidi: 69, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/euphonium_treble', {label: 'Euphonium', minmidi: 40, maxmidi: 70 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/high_bb_horn', {label: 'Horn in B♭', minmidi: 44, maxmidi: 77 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_chalumeau', {label: 'Tenor Chalumeau', minmidi: 48, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/theremin', {label: 'Theremin', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_shawm', {label: 'Tenor Shawm', minmidi: 48, maxmidi: 64 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/baritone_horn_treble', {label: 'Baritone Horn', minmidi: 40, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabass_recorder', {label: 'Contrabass Recorder', minmidi: 41, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/d_dizi', {label: 'Dizi', minmidi: 69, maxmidi: 95 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/orff_bass_metallophone', {label: 'Orff Bass Metallophone', minmidi: 48, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_dizi', {label: 'C Dizi', minmidi: 67, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_kelhorn', {label: 'Tenor Kelhorn', minmidi: 48, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_d10low_d', {label: '10 Hole Low D Diatonic Harmonica', minmidi: 50, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_kelhorn', {label: 'Soprano Kelhorn', minmidi: 60, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_d12a', {label: '10 Hole A Diatonic Harmonica', minmidi: 57, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/mellophone', {label: 'Mellophone', minmidi: 47, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_steel_drums', {label: 'Alto Steel Drums', minmidi: 56, maxmidi: 85 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/balalaika_prima', {label: 'Prima Balalaika', minmidi: 64, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/reed_contrabass', {label: 'Reed Contrabass', minmidi: 22, maxmidi: 57 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/square_synth', {label: 'Square Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/roto_toms', {label: 'Roto-Toms', minmidi: 40, maxmidi: 76 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bandoneon', {label: 'Bandoneon', minmidi: 36, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/vibraphone', {label: 'Vibraphone', minmidi: 53, maxmidi: 89 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_marimba', {label: 'Bass Marimba', minmidi: 36, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_viol', {label: 'Tenor Viol', minmidi: 43, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_shawm', {label: 'Soprano Shawm', minmidi: 60, maxmidi: 76 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/crotales', {label: 'Crotales', minmidi: 84, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_saxophone', {label: 'Bass Saxophone', minmidi: 32, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabass_trombone', {label: 'Contrabass Trombone', minmidi: 28, maxmidi: 55 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/shamisen', {label: 'Shamisen', minmidi: 50, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/subcontrabass_saxophone', {label: 'Subcontrabass Saxophone', minmidi: 20, maxmidi: 52 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/boy_soprano', {label: 'Boy Soprano', minmidi: 60, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/toy_piano', {label: 'Toy Piano', minmidi: 21, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_trombone', {label: 'Alto Trombone', minmidi: 45, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/vienna_horn', {label: 'Vienna Horn', minmidi: 35, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/rackett', {label: 'Rackett', minmidi: 34, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/french_flageolet', {label: 'French Flageolet', minmidi: 80, maxmidi: 105 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/ophicleide', {label: 'Ophicleide', minmidi: 35, maxmidi: 63 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/flugelhorn', {label: 'Flugelhorn', minmidi: 52, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_steel_drums', {label: 'Bass Steel Drums', minmidi: 36, maxmidi: 53 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/posthorn', {label: 'Posthorn', minmidi: 34, maxmidi: 67 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/conch', {label: 'Conch', minmidi: 24, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/mellophon_bugle', {label: 'Mellophone Bugle', minmidi: 41, maxmidi: 77 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_soprano_ocarina', {label: 'F Soprano Ocarina', minmidi: 77, maxmidi: 91 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bugle', {label: 'Bugle', minmidi: 67, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/grand_piano', {label: 'Grand Piano', minmidi: 21, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sheng', {label: 'Sheng', minmidi: 55, maxmidi: 90 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/dulcian', {label: 'Dulcian', minmidi: 40, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_gemshorn', {label: 'Alto Gemshorn', minmidi: 65, maxmidi: 80 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/banjo', {label: 'Banjo', minmidi: 48, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/saxophone', {label: 'Saxophone', minmidi: 44, maxmidi: 77 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_d12f', {label: '10 Hole F Diatonic Harmonica', minmidi: 65, maxmidi: 101 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica', {label: 'Harmonica', minmidi: 60, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tarogato', {label: 'Tarogato', minmidi: 58, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano_recorder', {label: 'Soprano Recorder', minmidi: 72, maxmidi: 93 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabass_clarinet', {label: 'Contrabass Clarinet', minmidi: 25, maxmidi: 65 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/soprano', {label: 'Soprano', minmidi: 60, maxmidi: 79 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_mandola', {label: 'Tenor Mandola', minmidi: 48, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_bass_clarinet_bass_clef', {label: 'B♭ Bass Clarinet (Bass Clef)', minmidi: 37, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_bass_trumpet', {label: 'B♭ Bass Trumpet', minmidi: 39, maxmidi: 66 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_soprano_ocarina', {label: 'B♭ Soprano Ocarina', minmidi: 70, maxmidi: 84 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harmonica_d12_g', {label: '10 Hole G Diatonic Harmonica', minmidi: 55, maxmidi: 91 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/pad_synth', {label: 'Pad Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_sousaphone', {label: 'B♭ Sousaphone', minmidi: 30, maxmidi: 60 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/guitar_steel', {label: 'Acoustic Guitar', minmidi: 40, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_trumpet', {label: 'B♭ Trumpet', minmidi: 52, maxmidi: 80 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/alto_shawm', {label: 'Alto Shawm', minmidi: 53, maxmidi: 69 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/prim', {label: 'Prim', minmidi: 64, maxmidi: 91 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/theorbo_14_course', {label: 'Theorbo', minmidi: 31, maxmidi: 71 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/new_age_synth', {label: 'New Age Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/c_quena', {label: 'C Quena', minmidi: 72, maxmidi: 92 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/violins', {label: 'Violins', minmidi: 55, maxmidi: 88 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/warm_synth', {label: 'Warm Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/english_horn', {label: 'English Horn', minmidi: 52, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tenor_sackbut', {label: 'Tenor Sackbut', minmidi: 40, maxmidi: 70 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/g_quena', {label: 'G Quena', minmidi: 67, maxmidi: 87 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_dizi', {label: 'F Dizi', minmidi: 72, maxmidi: 98 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/contrabass', {label: 'Contrabass', minmidi: 28, maxmidi: 62 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/fife', {label: 'B♭ Fife', minmidi: 74, maxmidi: 103 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bass_recorder', {label: 'Bass Recorder', minmidi: 53, maxmidi: 74 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/rain_synth', {label: 'Rain Synthesizer', minmidi: 36, maxmidi: 96 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/eb_contrabass_ophicleide', {label: 'E♭ Contrabass Ophicleide', minmidi: 26, maxmidi: 55 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/bb_wagner_tuba', {label: 'B♭ Wagner Tuba', minmidi: 40, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/f_baroque_trumpet', {label: 'Baroque Trumpet in F', minmidi: 65, maxmidi: 86 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/greatbass_crumhorn', {label: 'Greatbass Crumhorn', minmidi: 36, maxmidi: 50 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/guitar_nylon', {label: 'Classical Guitar', minmidi: 40, maxmidi: 83 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/mandocello', {label: 'Mandocello', minmidi: 36, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/a_duduk', {label: 'A Duduk', minmidi: 66, maxmidi: 81 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/high_c_horn', {label: 'High C Horn', minmidi: 46, maxmidi: 75 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/harp', {label: 'Harp', minmidi: 23, maxmidi: 104 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/tubaphone', {label: 'Tubaphone', minmidi: 84, maxmidi: 108 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/piccolo_oboe', {label: 'Piccolo Oboe', minmidi: 61, maxmidi: 90 }],
['http://fast-project.annalist.net/annalist/c/MusicalInstruments/d/Instrument/sousaphone', {label: 'Sousaphone', minmidi: 28, maxmidi: 58 }]
])

function matchServiceLabel(uri) {
  let m = serviceLabels.get(uri)
  if (!m) { console.log("No Label for:", uri)}
  return m
}
module.exports.matchServiceLabel = matchServiceLabel

function instrumentLabel(uri) {
  let m // = instrumentLabels.get(uri)
  let d = instrumentDetails.get(uri)
  if (d) { m = d.label }
  if (!m) { console.log("No Label for:", uri)}
  return m
}
module.exports.instrumentLabel = instrumentLabel

function getInstrumentDetails(uri) {
  let d = instrumentDetails.get(String(uri))
  if (!d) { console.log("No details for:", uri)}
  return d
}
module.exports.getInstrumentDetails = getInstrumentDetails
