// Map MEI note to SPN and/or MIDI note

/*

See: https://github.com/oerc-music/nin-remixer-public/blob/master/notes/meetings/2018-08-17-meeting.md#mei-note-extraction

Notes on a conventional score are described by a combination of values:

1. Note position on score: e-f-g-a-b-c-d-e-f (Ignoring, for now, notes that lie outside the regular score positions)

2. Clef, which defines a relationship between score lines and notes in some complicated fashion.

3. A key signature that adjusts (sharpen or flatten) some note positions selectively 

4. Accidentals that adjust specific notes in a measure/bar.

This information is represented in MEI generated by NiN as:

1. `note@pname` - "pitch name" - designates a note using just its name, without any sharp of flat designation ([NiN source](https://github.com/davidderoure/NumbersIntoNotes/blob/e83a615aef0eb735d814806bb7284a9774eb80f1/NumbersIntoNotesBeta.js#L2505) - where `par` is a MIDI note number).

2. `note@oct` - designates an octave number, where so that C4 is MIDI note 60, and each octave ranges C to B ([NiN code](https://github.com/davidderoure/NumbersIntoNotes/blob/e83a615aef0eb735d814806bb7284a9774eb80f1/NumbersIntoNotesBeta.js#L2507)).

3. Key signature is provided by a containing `<scoredef>` element, `key.sig` attriubute, whose value is one of:

    ["0s", "7s", "2s", "3f", "4s", "1f", "6s", "1s", "4f", "3s", "2f", "5s"]

([Nin source](https://github.com/davidderoure/NumbersIntoNotes/blob/e83a615aef0eb735d814806bb7284a9774eb80f1/NumbersIntoNotesBeta.js#L2357), et. seq.)
*/

/* map notename,octave -> MIDI number                                */
/* See https://en.wikipedia.org/wiki/Scientific_pitch_notation table */
note_midi_table =
    { "C":  { "-1":   0, "0":  12, "1":  24, "2":  36, "3":  48, "4":  60, "5":  72, "6":  84, "7":  96, "8": 108, "9": 120 }
    , "C#": { "-1":   1, "0":  13, "1":  25, "2":  37, "3":  49, "4":  61, "5":  73, "6":  85, "7":  97, "8": 109, "9": 121 }
    , "Db": { "-1":   1, "0":  13, "1":  25, "2":  37, "3":  49, "4":  61, "5":  73, "6":  85, "7":  97, "8": 109, "9": 121 }
    , "D":  { "-1":   2, "0":  14, "1":  26, "2":  38, "3":  50, "4":  62, "5":  74, "6":  86, "7":  98, "8": 110, "9": 122 }
    , "D#": { "-1":   3, "0":  15, "1":  27, "2":  39, "3":  51, "4":  63, "5":  75, "6":  87, "7":  99, "8": 111, "9": 123 }
    , "Eb": { "-1":   3, "0":  15, "1":  27, "2":  39, "3":  51, "4":  63, "5":  75, "6":  87, "7":  99, "8": 111, "9": 123 }
    , "E":  { "-1":   4, "0":  16, "1":  28, "2":  40, "3":  52, "4":  64, "5":  76, "6":  88, "7": 100, "8": 112, "9": 124 }
    , "F":  { "-1":   5, "0":  17, "1":  29, "2":  41, "3":  53, "4":  65, "5":  77, "6":  89, "7": 101, "8": 113, "9": 125 }
    , "F#": { "-1":   6, "0":  18, "1":  30, "2":  42, "3":  54, "4":  66, "5":  78, "6":  90, "7": 102, "8": 114, "9": 126 }
    , "Gb": { "-1":   6, "0":  18, "1":  30, "2":  42, "3":  54, "4":  66, "5":  78, "6":  90, "7": 102, "8": 114, "9": 126 }
    , "G":  { "-1":   7, "0":  19, "1":  31, "2":  43, "3":  55, "4":  67, "5":  79, "6":  91, "7": 103, "8": 115, "9": 127 }
    , "G#": { "-1":   8, "0":  20, "1":  32, "2":  44, "3":  56, "4":  68, "5":  80, "6":  92, "7": 104, "8": 116, "9": 128 }
    , "Ab": { "-1":   8, "0":  20, "1":  32, "2":  44, "3":  56, "4":  68, "5":  80, "6":  92, "7": 104, "8": 116, "9": 128 }
    , "A":  { "-1":   9, "0":  21, "1":  33, "2":  45, "3":  57, "4":  69, "5":  81, "6":  93, "7": 105, "8": 117, "9": 129 }
    , "A#": { "-1":  10, "0":  22, "1":  34, "2":  46, "3":  58, "4":  70, "5":  82, "6":  94, "7": 106, "8": 118, "9": 130 }
    , "Bb": { "-1":  10, "0":  22, "1":  34, "2":  46, "3":  58, "4":  70, "5":  82, "6":  94, "7": 106, "8": 118, "9": 130 }
    , "B":  { "-1":  11, "0":  23, "1":  35, "2":  47, "3":  59, "4":  71, "5":  83, "6":  95, "7": 107, "8": 119, "9": 131 }
    };

/* map keysig,notename -> notename                        */
/* See https://en.wikipedia.org/wiki/Key_signature tables */
keysig_note_table =
    { "0s": { "C": "C" , "D": "D" , "E": "E" , "F": "F" , "G": "G" , "A": "A" , "B": "B"  }
    , "1s": { "C": "C" , "D": "D" , "E": "E" , "F": "F#", "G": "G" , "A": "A" , "B": "B"  }
    , "2s": { "C": "C#", "D": "D" , "E": "E" , "F": "F#", "G": "G" , "A": "A" , "B": "B"  }
    , "3s": { "C": "C#", "D": "D" , "E": "E" , "F": "F#", "G": "G#", "A": "A" , "B": "B"  }
    , "4s": { "C": "C#", "D": "D#", "E": "E" , "F": "F#", "G": "G#", "A": "A" , "B": "B"  }
    , "5s": { "C": "C#", "D": "D#", "E": "E" , "F": "F#", "G": "G#", "A": "A#", "B": "B"  }
    , "6s": { "C": "C#", "D": "D#", "E": "F" , "F": "F#", "G": "G#", "A": "A#", "B": "B"  }
    , "7s": { "C": "C#", "D": "D#", "E": "F" , "F": "F#", "G": "G#", "A": "A#", "B": "C"  }

    , "0f": { "C": "C" , "D": "D" , "E": "E" , "F": "F" , "G": "G" , "A": "A" , "B": "B"  }
    , "1f": { "C": "C" , "D": "D" , "E": "E" , "F": "F" , "G": "G" , "A": "A" , "B": "Bb" }
    , "2f": { "C": "C" , "D": "D" , "E": "Eb", "F": "F" , "G": "G" , "A": "A" , "B": "Bb" }
    , "3f": { "C": "C" , "D": "D" , "E": "Eb", "F": "F" , "G": "G" , "A": "Ab", "B": "Bb" }
    , "4f": { "C": "C" , "D": "Db", "E": "Eb", "F": "F" , "G": "G" , "A": "Ab", "B": "Bb" }
    , "5f": { "C": "C" , "D": "Db", "E": "Eb", "F": "F" , "G": "Gb", "A": "Ab", "B": "Bb" }
    , "6f": { "C": "B" , "D": "Db", "E": "Eb", "F": "F" , "G": "Gb", "A": "Ab", "B": "Bb" }
    , "7f": { "C": "B" , "D": "Db", "E": "Eb", "F": "E" , "G": "Gb", "A": "Ab", "B": "Bb" }
    };

/* SPN Octave adjustment when a key signature is applied to a base note */
/* See https://en.wikipedia.org/wiki/Scientific_pitch_notation table    */
keysig_octave_table =
    { "0s": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "1s": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "2s": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "3s": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "4s": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "5s": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "6s": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "7s": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B": +1 }
    , "0f": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "1f": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "2f": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "3f": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "4f": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "5f": { "C":  0, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "6f": { "C": -1, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    , "7f": { "C": -1, "D": 0, "E": 0, "F": 0, "G": 0, "A": 0, "B":  0 }
    };

/* Convert a note from an MEI score, as mofified by key signature, to a */
/* MIDI note number.                                                    */
/*   accid (accidental) is "s", "n", "f" or ""                          */
function mei_note_midi(keysig, pname, octave, accid) {
    var spname = pname;
    if (accid !== "n") {
        spname  = keysig_note_table[keysig][pname];      // SPN pitch name with keysig sharp/flat applied
        octave += keysig_octave_table[keysig][pname];    // Adjust octave for lookup
        /* @@TODO: Check octave still in range */
    }
    midinum = note_midi_table[spname][octave];
    if ( accid === "s" ) midinum += 1;
    if ( accid === "f" ) midinum -= 1;
    return midinum;
}

function assert(condition, message) {
    if (!condition) {
        message = message || "Assertion failed";
        if (typeof Error !== "undefined") {
            throw new Error(message);
        }
        throw message; // Fallback
    }
}

function log(message, val) {
    console.log(message, val);
}

function test_mei_note_midi() {
    assert(mei_note_midi("0s", "C", 4, "")  == 60, "0s C");
    assert(mei_note_midi("7s", "C", 4, "")  == 61, "7s C");
    assert(mei_note_midi("0s", "B", 4, "")  == 71, "0s B");
    assert(mei_note_midi("7s", "B", 4, "")  == 72, "7s B"); /* Octave rollover */
    assert(mei_note_midi("0f", "C", 4, "")  == 60, "0f C");
    assert(mei_note_midi("6f", "C", 4, "")  == 59, "6f C"); /* Octave rollover */
    /* accidental "n" */
    log("assert(mei_note_midi(7s, C, 4, n) ", mei_note_midi("7s", "C", 4, "n") );
    assert(mei_note_midi("0s", "C", 4, "n") == 60);
    assert(mei_note_midi("7s", "C", 4, "n") == 60);
    assert(mei_note_midi("7s", "B", 4, "n") == 71);
    assert(mei_note_midi("6f", "C", 4, "n") == 60);
    /* accidental "s" */
    assert(mei_note_midi("0s", "C", 4, "s") == 61);
    assert(mei_note_midi("7s", "C", 4, "s") == 62);
    assert(mei_note_midi("0s", "B", 4, "s") == 72);
    assert(mei_note_midi("7s", "B", 4, "s") == 73); /* Octave rollover */
    assert(mei_note_midi("0f", "C", 4, "s") == 61);
    assert(mei_note_midi("6f", "C", 4, "s") == 60); /* Octave rollover */
    /* accidental "f" */
    assert(mei_note_midi("0s", "C", 4, "f") == 59);
    assert(mei_note_midi("7s", "C", 4, "f") == 60);
    assert(mei_note_midi("0s", "B", 4, "f") == 70);
    assert(mei_note_midi("7s", "B", 4, "f") == 71); /* Octave rollover */
    assert(mei_note_midi("0f", "C", 4, "f") == 59);
    assert(mei_note_midi("6f", "C", 4, "f") == 58); /* Octave rollover */
    alert("tests run");
}

